[plugin]
repository = "https://github.com/Elypha/SimpleMarketBoard.git"
commit = "3e7d9c0a6be33b4053f82ce8c1f9cfe1d1e3be3b"
owners = ["Elypha"]
project_path = "SimpleMarketBoard"
changelog = """
v1.10.0.0
New Features:
- NA

Fixed Problems:
- API 13 support

+ 1.10.0.0: ...
"""
